# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rist_app.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erist_app.proto\x12\x07RistApp\"=\n\x11\x41ppStatusResponse\x12(\n\napp_status\x18\x01 \x01(\x0e\x32\x14.RistApp.AppResponse\"\xc5\x01\n\rRistAppconfig\x12\x11\n\tInputType\x18\x01 \x01(\t\x12\x10\n\x08InputUrl\x18\x02 \x01(\t\x12\x11\n\tInputPort\x18\x03 \x01(\t\x12\x0c\n\x04Mode\x18\x04 \x01(\t\x12\x12\n\nOutputType\x18\x05 \x01(\t\x12\x11\n\tOutputUrl\x18\x06 \x01(\t\x12\x12\n\nOutputPort\x18\x07 \x01(\t\x12\x0f\n\x07Profile\x18\x08 \x01(\t\x12\x12\n\nEncryption\x18\t \x01(\t\x12\x0e\n\x06Secret\x18\n \x01(\t\"\x07\n\x05\x45mpty*L\n\x0b\x41ppResponse\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0b\n\x07STOPPED\x10\x02\x12\x16\n\x12SUCCESSFULL_UPDATE\x10\x03\x32\x92\x02\n\x07RistApp\x12\x44\n\x0cStartRistApp\x12\x16.RistApp.RistAppconfig\x1a\x1a.RistApp.AppStatusResponse\"\x00\x12;\n\x0bStopRistApp\x12\x0e.RistApp.Empty\x1a\x1a.RistApp.AppStatusResponse\"\x00\x12=\n\rStatusRistApp\x12\x0e.RistApp.Empty\x1a\x1a.RistApp.AppStatusResponse\"\x00\x12\x45\n\rUpdateRistApp\x12\x16.RistApp.RistAppconfig\x1a\x1a.RistApp.AppStatusResponse\"\x00\x42\x1bZ\x19ristapp/grpc_app/rist_appb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rist_app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031ristapp/grpc_app/rist_app'
  _globals['_APPRESPONSE']._serialized_start=299
  _globals['_APPRESPONSE']._serialized_end=375
  _globals['_APPSTATUSRESPONSE']._serialized_start=27
  _globals['_APPSTATUSRESPONSE']._serialized_end=88
  _globals['_RISTAPPCONFIG']._serialized_start=91
  _globals['_RISTAPPCONFIG']._serialized_end=288
  _globals['_EMPTY']._serialized_start=290
  _globals['_EMPTY']._serialized_end=297
  _globals['_RISTAPP']._serialized_start=378
  _globals['_RISTAPP']._serialized_end=652
# @@protoc_insertion_point(module_scope)
